---
deployment:
  tasks:
    - export DEPLOYPATH=/home/thangtun/sub.thangtuner.com/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R 2025 $DEPLOYPATH
    - /bin/cp -R 2026 $DEPLOYPATH
    - /bin/cp -R about-me $DEPLOYPATH
    - /bin/cp -R about-me-but-serious-corpo $DEPLOYPATH
    - /bin/cp -R music $DEPLOYPATH
    - /bin/cp -R other-works $DEPLOYPATH
    - /bin/cp -R studies $DEPLOYPATH
    - /bin/cp -R wp-content $DEPLOYPATH
    - /bin/cp -R wp-includes $DEPLOYPATH